import { Geist, Geist_Mono, Marck_Script } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const marckScript = Marck_Script({
  variable: "--font-marck-script",
  subsets: ["latin"],
  weight: '400'
})

export const metadata = {
  title: "MacroWizard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{padding: '30px 15px'}}>
        {children}
      </body>
    </html>
  );
}
